# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Make Seattle Better
email: your-email@domain.com
author: Substantial
description: > # "Make Seattle Better is a place where Seattleites can
collaborate on ideas of how to improve our wonderful city."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url:
